// Generated by ReScript, PLEASE EDIT WITH CARE

import * as App from "../src/App.mjs";
import * as React from "react";
import * as Vitest from "rescript-vitest/src/Vitest.mjs";
import * as Vitest$1 from "vitest";
import * as React$1 from "@testing-library/react";

Vitest.describe("App", undefined, (function (param) {
        return Vitest.test("renders component without crashing", undefined, (function (t) {
                      t.hasAssertions(1);
                      React$1.render(React.createElement(App.make, {}));
                      Vitest$1.expect(React$1.screen.getByText("Hello Vite + React + ReScript!")).toBeInTheDocument();
                      
                    }));
      }));

export {
  
}
/*  Not a pure module */
